### ISSUE TITLE
Decide how we want to limit rate of fire

### ISSUE THREAD

**Issue by JakeCalkins** [mjd4686/WiFi-Router-Hyper-Simulator-X3000#14]
Do we add reload?
Do we add overheat?
Do we add a secondary weapon? (ie. swap the weapon model and lower the rate of fire or increase the recoil after X shots with primary to encourage ammo conservation)

**Comment by Demonwi** [comment]
Potentially have different characters just be different weapons chosen at the start.  1 weapon allowed.  Starter weapon is a hitscan raygun with .5 seconds between each shot.  Others can be discussed.

**Comment by JakeCalkins** [comment]
cooldown implemented.
