### ISSUE TITLE
Add a score system

### ISSUE THREAD

**Issue by JakeCalkins** [mjd4686/WiFi-Router-Hyper-Simulator-X3000#7]
Need a way to calculate user score based off the clock and their accuracy of damaging the routers.

**Comment by JakeCalkins** [comment]
Components of score:
- Time
- number routers destroyed
   - tier 1 and 2 have set number of points
   - Beacons destroyed should be worth this: 50 points per beacon
 - Hubs destroyed should be worth: number_of_beacons_unbroken * 100 points
- Accuracy? Would need to track number raycasts on target

**Comment by JakeCalkins** [comment]
Leaderboard needs to save:
- Username (leaderboard UI should prompt for one)
- Score
- Time
- Win or loss (determined by if you run out of time before all routers are destroyed)

Saved to a text file
UI needs to be able to read this text file to display the leaderboard

**Comment by Demonwi** [comment]
10 * seconds remaining
100 pts Tier 1 router
500 pts Tier 2 router
50 pts per beacon
hub = 100pts per beacon remaining
additional 1000 points for winning.  
Accuracy Awards:
(Only receive top accolade)
100%: Aimbotter + 2000 pts
>=90%: File Sniper + 1000 pts
>=70%: Data Marksman + 500 pts
>=50%: Seek and Destroy + 250 pts
>=30%: Eye on the Prize + 100 pts
>0%: Spray and Pray + 0 pts
0%: Absolute Zero +1 pts
